# Generated by Django 6.0.3 on 2026-03-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ttd_digital',
            field=models.ImageField(blank=True, null=True, upload_to='ttd_digital/'),
        ),
    ]
