# Generated by Django 6.0.3 on 2026-03-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_userprofile_ttd_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
