# Generated by Django 6.0.3 on 2026-03-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0005_delete_legacy_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['nama']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
