# Generated by Django 6.0.4 for SILEBAT Pelatihan index alignment.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0007_pelatihan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pelatihan',
            new_name='pengguna_pe_user_id_4dd45d_idx',
            old_name='pengguna_pe_user_id_5e6d87_idx',
        ),
        migrations.RenameIndex(
            model_name='pelatihan',
            new_name='pengguna_pe_tipe_pe_129eec_idx',
            old_name='pengguna_pe_tipe_pe_7b2f36_idx',
        ),
    ]
