# Generated by Django 6.0.4 on 2026-05-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_refactor_landing_peralatan_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingperalatancard',
            name='jenis_barang',
            field=models.CharField(max_length=160, verbose_name='Jenis Barang'),
        ),
    ]
