# Generated by Django 6.0.4 on 2026-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_landing_peralatan_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingperalatancard',
            name='metode_pengukuran',
            field=models.CharField(blank=True, max_length=180, verbose_name='Metode Pengukuran'),
        ),
    ]
