# Generated by Django 6.0.3 on 2026-04-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangpenunjangoperasional',
            name='kategori_barang',
            field=models.CharField(choices=[('Penunjang Operasional Alat', 'Penunjang Operasional Alat'), ('Penunjang Operasional Lapangan', 'Penunjang Operasional Lapangan'), ('Penunjang Operasional K3 dan Pelindung', 'Penunjang Operasional K3 dan Pelindung'), ('Penunjang Operasional Ruangan/Kantor', 'Penunjang Operasional Ruangan/Kantor')], max_length=60),
        ),
    ]
