# Generated by Django 6.0.3 on 2026-04-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_barangpenunjangoperasional_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baranglaboratorium',
            name='kondisi_barang',
            field=models.CharField(choices=[('Baik', 'Baik'), ('Dalam Pemeliharaan', 'Dalam Pemeliharaan'), ('Dalam Perbaikan', 'Dalam Perbaikan'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang')], default='Baik', max_length=30),
        ),
        migrations.AlterField(
            model_name='fasilitasruangan',
            name='kondisi_barang',
            field=models.CharField(choices=[('Baik', 'Baik'), ('Dalam Pemeliharaan', 'Dalam Pemeliharaan'), ('Dalam Perbaikan', 'Dalam Perbaikan'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang')], default='Baik', max_length=30),
        ),
    ]
