# Generated by Django 6.0.3 on 2026-04-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_barangpenunjang_volume_rusak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baranglaboratorium',
            name='kategori_barang',
            field=models.CharField(choices=[('Borehole Camera', 'Borehole Camera'), ('Drone', 'Drone'), ('Geolistrik', 'Geolistrik'), ('Instrumen Keairan', 'Instrumen Keairan'), ('Logging', 'Logging'), ('Topografi (TS)', 'Topografi (TS)'), ('Pendukung Survei Lapangan', 'Pendukung Survei Lapangan'), ('Penunjang Survei Lapangan', 'Penunjang Survei Lapangan')], max_length=40, null=True),
        ),
    ]
