# Generated by Django 6.0.4 on 2026-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_asset_bervolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitasruangan',
            name='komponen_pemeliharaan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='peralatanlaboratorium',
            name='komponen_pemeliharaan',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
