"""
Django settings for silebat project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, urlparse, unquote

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ON_VERCEL = os.getenv("VERCEL") == "1"

# Di Vercel, gunakan Environment Variables dari dashboard Vercel.
# File .env lokal sengaja tidak dimuat agar konfigurasi Docker/dev
# tidak ikut terbawa ke production serverless.
if not ON_VERCEL:
    load_dotenv(BASE_DIR / ".env")


def env_bool(key, default=False):
    val = os.getenv(key)
    if val is None:
        return default
    return val.strip().lower() in ["1", "true", "yes", "on"]


def env_list(key, default=""):
    return [item.strip() for item in os.getenv(key, default).split(",") if item.strip()]


def first_env(*keys):
    for key in keys:
        value = os.getenv(key, "").strip()
        if value:
            return value
    return ""


def add_unique(items, value):
    if value and value not in items:
        items.append(value)


def vercel_hosts():
    hosts = []
    for key in ["VERCEL_URL", "VERCEL_PROJECT_PRODUCTION_URL"]:
        host = os.getenv(key, "").strip()
        if host:
            add_unique(hosts, host.replace("https://", "").replace("http://", ""))
    return hosts


def db_from_url(url):
    parsed = urlparse(url)
    engine = "django.db.backends.postgresql"
    query = parse_qs(parsed.query)
    cfg = {
        "ENGINE": engine,
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }
    sslmode = query.get("sslmode", [""])[0]
    if DB_CONN_MAX_AGE:
        cfg["CONN_MAX_AGE"] = DB_CONN_MAX_AGE
    if sslmode:
        cfg["OPTIONS"] = {"sslmode": sslmode}
    return cfg


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", not ON_VERCEL)

DEFAULT_HOSTS = "localhost,127.0.0.1,0.0.0.0,silebat-cujz.vercel.app"
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", DEFAULT_HOSTS)
for host in vercel_hosts():
    add_unique(ALLOWED_HOSTS, host)

PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "https://silebat-cujz.vercel.app" if ON_VERCEL else "http://127.0.0.1:8000")
DASHBOARD_TV_SLUG = os.getenv("DASHBOARD_TV_SLUG", "lab-tv-realtime-silebat-7q4m2x9v")

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
for origin in [PUBLIC_BASE_URL, "https://silebat-cujz.vercel.app"]:
    if origin.startswith(("http://", "https://")):
        add_unique(CSRF_TRUSTED_ORIGINS, origin.rstrip("/"))
for host in vercel_hosts():
    add_unique(CSRF_TRUSTED_ORIGINS, f"https://{host}")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.core",
    "apps.dashboard",
    "apps.landing.apps.LandingConfig",
    "apps.chatbot.apps.ChatbotConfig",
    "apps.operasional.apps.OperasionalConfig",
    "apps.master_data.apps.MasterDataConfig",
    "apps.peminjaman.apps.PeminjamanConfig",
    "apps.verifikasi.apps.VerifikasiConfig",
    "apps.notifikasi.apps.NotifikasiConfig",
    "apps.pengguna.apps.PenggunaConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.role_access",
                "apps.notifikasi.context_processors.navbar_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_URL = first_env("DATABASE_URL", "POSTGRES_URL", "POSTGRES_PRISMA_URL", "POSTGRES_URL_NON_POOLING")
DB_CONN_MAX_AGE = int(os.getenv("DB_CONN_MAX_AGE", "0"))

DATABASES = {
    "default": db_from_url(DB_URL)
    if DB_URL
    else {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DB_NAME", "silebat_db"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": DB_CONN_MAX_AGE,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "id-id"

TIME_ZONE = "Asia/Jakarta"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


AUTH_USER_MODEL = "pengguna.User"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", ON_VERCEL)
    SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", ON_VERCEL)
    CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", ON_VERCEL)
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
