# Generated by Django 6.0.3 on 2026-04-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifikasi', '0002_notification_schedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notifikasi__recipie_34c3e3_idx',
            old_name='notifikasi_n_recipie_9a6625_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notifikasi__recipie_f54d4f_idx',
            old_name='notifikasi_n_recipie_04b7e6_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notifikasi__categor_c96810_idx',
            old_name='notifikasi_n_categor_e32f7a_idx',
        ),
    ]
