# Generated by Django 6.0.4 on 2026-06-09 23:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0015_baranglaboratorium_komponen_pemeliharaan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PemeliharaanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komponen', models.CharField(max_length=100)),
                ('kondisi', models.CharField(choices=[('Baik', 'Baik'), ('Perlu Perbaikan', 'Perlu Perbaikan')], default='Baik', max_length=30)),
                ('tindakan_perbaikan', models.CharField(blank=True, choices=[('Perbaikan Mandiri', 'Perbaikan Mandiri'), ('Perbaikan Eksternal', 'Perbaikan Eksternal')], max_length=30)),
                ('uraian_perbaikan', models.TextField(blank=True)),
                ('tanggal_mulai_perbaikan', models.DateTimeField(blank=True, null=True)),
                ('tanggal_selesai_perbaikan', models.DateTimeField(blank=True, null=True)),
                ('uraian_kerusakan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Item Pemeliharaan',
                'verbose_name_plural': 'Item Pemeliharaan',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PemeliharaanFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('pemeriksaan', 'Dokumentasi Pemeriksaan'), ('perbaikan', 'Dokumentasi Perbaikan'), ('kerusakan', 'Dokumentasi Kerusakan')], max_length=20)),
                ('foto', models.ImageField(upload_to='pemeliharaan/foto/')),
                ('urutan', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pemeliharaan.pemeliharaanitem')),
            ],
            options={
                'verbose_name': 'Foto Pemeliharaan',
                'verbose_name_plural': 'Foto Pemeliharaan',
                'ordering': ['jenis', 'urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PemeliharaanPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pengajuan', models.CharField(blank=True, max_length=30, unique=True)),
                ('tanggal_pemeriksaan', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot_nama_barang', models.CharField(blank=True, max_length=200)),
                ('snapshot_kode_laboratorium', models.CharField(blank=True, max_length=100)),
                ('snapshot_tipe_merek_barang', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_pemeliharaan', to='master_data.baranglaboratorium')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_pemeliharaan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengajuan Pemeliharaan',
                'verbose_name_plural': 'Pengajuan Pemeliharaan',
                'ordering': ['-tanggal_pemeriksaan', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pemeliharaanitem',
            name='pengajuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pemeliharaan.pemeliharaanpengajuan'),
        ),
    ]
