# Generated by Django 6.0.4 on 2026-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemeliharaan', '0004_status_ditolak'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeliharaanpengajuan',
            name='master_awal_disimpan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pemeliharaanpengajuan',
            name='tanggal_pemeliharaan_sebelum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemeliharaanpengajuan',
            name='tanggal_perbaikan_sebelum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
