# Generated by Django 6.0.4 on 2026-06-12 08:44

from django.db import migrations, models


def backfill_snapshot_status(apps, schema_editor):
    Pengajuan = apps.get_model("pemeliharaan", "PemeliharaanPengajuan")
    for pengajuan in Pengajuan.objects.select_related("alat").filter(alat__isnull=False).iterator():
        pengajuan.snapshot_status_barang = pengajuan.alat.status_barang or ""
        pengajuan.save(update_fields=["snapshot_status_barang"])


class Migration(migrations.Migration):

    dependencies = [
        ('pemeliharaan', '0005_snapshot_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeliharaanpengajuan',
            name='snapshot_status_barang',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(backfill_snapshot_status, migrations.RunPython.noop),
    ]
