# Generated by Django 6.0.4 on 2026-07-13 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_fasilitasruangan_komponen_pemeliharaan_and_more'),
        ('pemeliharaan', '0006_snapshot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PemeliharaanVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_vendor', models.CharField(max_length=200)),
                ('nama_pic', models.CharField(max_length=200)),
                ('nomor_hp_pic', models.CharField(max_length=30)),
                ('alamat', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kepala_lab_status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('revision', 'Dikembalikan')], default='pending', max_length=20)),
                ('kepala_lab_at', models.DateTimeField(blank=True, null=True)),
                ('kepala_lab_note', models.TextField(blank=True)),
                ('pimpinan_status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('revision', 'Dikembalikan')], default='pending', max_length=20)),
                ('pimpinan_at', models.DateTimeField(blank=True, null=True)),
                ('pimpinan_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Vendor Perbaikan',
                'verbose_name_plural': 'Data Vendor Perbaikan',
            },
        ),
        migrations.RemoveConstraint(
            model_name='pemeliharaanpengajuan',
            name='uq_pemeliharaan_alat_aktif',
        ),
        migrations.AlterField(
            model_name='pemeliharaanpengajuan',
            name='current_step',
            field=models.CharField(choices=[('draft', 'Draft'), ('kepala_lab', 'Verifikasi Pemeliharaan - Kepala Lab'), ('pimpinan', 'Verifikasi Pemeliharaan - Ketua Tim Layanan Teknis'), ('vendor_draft', 'Input Data Vendor'), ('vendor_kepala_lab', 'Verifikasi Data Vendor - Kepala Lab'), ('vendor_pimpinan', 'Verifikasi Data Vendor - Ketua Tim Layanan Teknis'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak'), ('dikembalikan', 'Dikembalikan ke Pemohon')], default='draft', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='pemeliharaanpengajuan',
            constraint=models.UniqueConstraint(condition=models.Q(('alat__isnull', False), ('current_step__in', ('draft', 'kepala_lab', 'pimpinan', 'vendor_draft', 'vendor_kepala_lab', 'vendor_pimpinan', 'dikembalikan'))), fields=('alat',), name='uq_pemeliharaan_alat_aktif'),
        ),
        migrations.AddField(
            model_name='pemeliharaanvendor',
            name='kepala_lab_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_lab_vendor_pemeliharaan_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pemeliharaanvendor',
            name='pengajuan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='pemeliharaan.pemeliharaanpengajuan'),
        ),
        migrations.AddField(
            model_name='pemeliharaanvendor',
            name='pimpinan_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pimpinan_vendor_pemeliharaan_processed', to=settings.AUTH_USER_MODEL),
        ),
    ]
