# Generated by Django 6.0.3 on 2026-04-03 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_alter_barangpenunjangoperasional_kategori_barang'),
        ('operasional', '0002_surveikegiatan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeminjamanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pengajuan', models.CharField(blank=True, max_length=30, unique=True)),
                ('nama_peminjam', models.CharField(max_length=255)),
                ('no_hp_peminjam', models.CharField(blank=True, max_length=50)),
                ('email_peminjam', models.EmailField(blank=True, max_length=254)),
                ('alamat_peminjam', models.TextField(blank=True)),
                ('nip_peminjam', models.CharField(blank=True, max_length=100)),
                ('survei_lainnya', models.CharField(blank=True, max_length=255)),
                ('instansi_tujuan_lainnya', models.CharField(blank=True, max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_hari', models.PositiveIntegerField(default=1)),
                ('current_step', models.CharField(choices=[('admin_lab', 'Verifikasi Admin Lab'), ('teknisi_lab', 'Proses Teknisi Lab'), ('user', 'Verifikasi User'), ('kepala_lab', 'Verifikasi Kepala Laboratorium'), ('pimpinan', 'Verifikasi Ketua Tim'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='admin_lab', max_length=30)),
                ('aset_sudah_dialokasikan', models.BooleanField(default=False)),
                ('admin_lab_status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('revision', 'Perbaiki'), ('ready', 'Siap / Selesai'), ('mismatch', 'Belum Sesuai')], default='pending', max_length=20)),
                ('admin_lab_at', models.DateTimeField(blank=True, null=True)),
                ('admin_lab_note', models.TextField(blank=True)),
                ('teknisi_lab_status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('revision', 'Perbaiki'), ('ready', 'Siap / Selesai'), ('mismatch', 'Belum Sesuai')], default='pending', max_length=20)),
                ('teknisi_lab_at', models.DateTimeField(blank=True, null=True)),
                ('teknisi_lab_note', models.TextField(blank=True)),
                ('user_verification_status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('revision', 'Perbaiki'), ('ready', 'Siap / Selesai'), ('mismatch', 'Belum Sesuai')], default='pending', max_length=20)),
                ('user_verification_at', models.DateTimeField(blank=True, null=True)),
                ('user_verification_note', models.TextField(blank=True)),
                ('kepala_lab_status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('revision', 'Perbaiki'), ('ready', 'Siap / Selesai'), ('mismatch', 'Belum Sesuai')], default='pending', max_length=20)),
                ('kepala_lab_at', models.DateTimeField(blank=True, null=True)),
                ('kepala_lab_note', models.TextField(blank=True)),
                ('pimpinan_status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('revision', 'Perbaiki'), ('ready', 'Siap / Selesai'), ('mismatch', 'Belum Sesuai')], default='pending', max_length=20)),
                ('pimpinan_at', models.DateTimeField(blank=True, null=True)),
                ('pimpinan_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_lab_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_lab_peminjaman_processed', to=settings.AUTH_USER_MODEL)),
                ('instansi_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_peminjaman', to='operasional.instansiklien')),
                ('kegiatan_survei', models.ManyToManyField(blank=True, to='operasional.surveikegiatan')),
                ('kepala_lab_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_lab_peminjaman_processed', to=settings.AUTH_USER_MODEL)),
                ('layanan_kegiatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_peminjaman', to='operasional.layanankegiatan')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_peminjaman', to=settings.AUTH_USER_MODEL)),
                ('pimpinan_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pimpinan_peminjaman_processed', to=settings.AUTH_USER_MODEL)),
                ('teknisi_lab_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teknisi_lab_peminjaman_processed', to=settings.AUTH_USER_MODEL)),
                ('tim_kegiatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_peminjaman', to='operasional.timkegiatan')),
            ],
            options={
                'verbose_name': 'Pengajuan Peminjaman',
                'verbose_name_plural': 'Pengajuan Peminjaman',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PeminjamanTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_peminjaman_actions', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='peminjaman.peminjamanrequest')),
            ],
            options={
                'verbose_name': 'Riwayat Verifikasi Peminjaman',
                'verbose_name_plural': 'Riwayat Verifikasi Peminjaman',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeminjamanBarangPenunjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(default=1)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.barangpenunjangoperasional')),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_penunjang_items', to='peminjaman.peminjamanrequest')),
            ],
            options={
                'verbose_name': 'Item Barang Penunjang Operasional',
                'verbose_name_plural': 'Item Barang Penunjang Operasional',
                'ordering': ['barang__nama_barang'],
                'unique_together': {('pengajuan', 'barang')},
            },
        ),
        migrations.CreateModel(
            name='PeminjamanBarangLaboratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.baranglaboratorium')),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_laboratorium_items', to='peminjaman.peminjamanrequest')),
            ],
            options={
                'verbose_name': 'Item Barang Laboratorium',
                'verbose_name_plural': 'Item Barang Laboratorium',
                'ordering': ['barang__nama_barang'],
                'unique_together': {('pengajuan', 'barang')},
            },
        ),
        migrations.CreateModel(
            name='PeminjamanBahanOperasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(default=1)),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.bahanoperasional')),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bahan_operasional_items', to='peminjaman.peminjamanrequest')),
            ],
            options={
                'verbose_name': 'Item Bahan Operasional',
                'verbose_name_plural': 'Item Bahan Operasional',
                'ordering': ['bahan__nama_barang'],
                'unique_together': {('pengajuan', 'bahan')},
            },
        ),
    ]
