# Generated by Django 6.0.3 on 2026-04-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0003_return_user_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamanrequest',
            name='return_current_step',
            field=models.CharField(choices=[('none', 'Belum Ada Pengembalian'), ('teknisi_verifikasi', 'Verifikasi Pengembalian Teknisi Lab'), ('user_verifikasi', 'Verifikasi User Pengembalian'), ('teknisi_ba', 'Penyusunan Berita Acara Hilang / Rusak'), ('kepala_ba', 'Verifikasi Berita Acara Kepala Laboratorium'), ('pimpinan_ba', 'Verifikasi Berita Acara Pimpinan'), ('teknisi_transfer', 'Proses Transfer Alat oleh Teknisi Lab'), ('kepala_transfer', 'Verifikasi Transfer Alat Kepala Laboratorium'), ('pimpinan_transfer', 'Verifikasi Transfer Alat Pimpinan'), ('completed', 'Pengembalian Selesai')], default='none', max_length=40),
        ),
    ]
