# Generated by Django 6.0.3 on 2026-04-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0006_peminjamanrequest_berkas_pendukung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamanrequest',
            name='current_step',
            field=models.CharField(choices=[('admin_lab', 'Verifikasi Peminjaman - Admin Lab'), ('teknisi_lab', 'Proses Peminjaman - Teknisi Lab'), ('user', 'Verifikasi Peminjaman - User'), ('kepala_lab', 'Verifikasi Peminjaman - Kepala Lab'), ('pimpinan', 'Verifikasi Peminjaman - Ketua Tim'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='admin_lab', max_length=30),
        ),
        migrations.AlterField(
            model_name='peminjamanrequest',
            name='return_current_step',
            field=models.CharField(choices=[('none', 'Belum Ada Pengembalian'), ('teknisi_verifikasi', 'Verifikasi Pengembalian - Teknisi Lab'), ('user_verifikasi', 'Verifikasi Pengembalian - User'), ('teknisi_ba', 'Verifikasi Pengembalian - Teknisi Lab'), ('kepala_ba', 'Verifikasi Pengembalian - Kepala Lab'), ('pimpinan_ba', 'Verifikasi Pengembalian - Ketua Tim'), ('teknisi_transfer', 'Verifikasi Pengembalian - Teknisi Lab'), ('kepala_transfer', 'Verifikasi Pengembalian - Kepala Lab'), ('pimpinan_transfer', 'Verifikasi Pengembalian - Ketua Tim'), ('completed', 'Pengembalian Selesai')], default='none', max_length=40),
        ),
    ]
