# Generated by ChatGPT on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operasional", "0002_surveikegiatan"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataKopDokumen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("kop_dokumen", models.ImageField(upload_to="operasional/kop_dokumen/")),
            ],
            options={
                "verbose_name": "Data Kop Dokumen",
                "verbose_name_plural": "Data Kop Dokumen",
            },
        ),
    ]
